# Site settings
title: Chris Cody
email: chris@chriscody.com
url: https://github.com/codeitlikecody
description: "Welcome to the portfolio of Chris Cody, a graduate data scientist and software engineer."
keywords: "data, science, software, engineer, Chris, Cody, portfolio"
skills: "Data Scientist - Software Engineer"
meta_author: Cody Chris

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 22435e #18bc9c #80B3FF
  primary-rgb: "34,67,94" #"24,288,156" #"128,179,255"
  secondary: 3f8956 #2c3e50 #FD6E8A
  secondary-dark: 2b5b38 #233140 #A2122F

# Footer settings
footer:
  copyright: Chris Cody
  location: Location
  social: Around the Web
  credits: Plant a tree

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: facebook
  #   url:
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket
  #   url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/codeitlikecody/
  - title: linkedin
    url: https://www.linkedin.com/in/chris-cody-13431830/

# Postal address (add as many lines as necessary)
address:
  - line: South Gippsland
  - line: VIC Australia

# Credits content
credits: '<a href="https://onetreeplanted.org/products/plant-trees"><svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="white" class="bi bi-tree" viewBox="0 0 16 16">
  <path d="M8.416.223a.5.5 0 0 0-.832 0l-3 4.5A.5.5 0 0 0 5 5.5h.098L3.076 8.735A.5.5 0 0 0 3.5 9.5h.191l-1.638 3.276a.5.5 0 0 0 .447.724H7V16h2v-2.5h4.5a.5.5 0 0 0 .447-.724L12.31 9.5h.191a.5.5 0 0 0 .424-.765L10.902 5.5H11a.5.5 0 0 0 .416-.777l-3-4.5zM6.437 4.758A.5.5 0 0 0 6 4.5h-.066L8 1.401 10.066 4.5H10a.5.5 0 0 0-.424.765L11.598 8.5H11.5a.5.5 0 0 0-.447.724L12.69 12.5H3.309l1.638-3.276A.5.5 0 0 0 4.5 8.5h-.098l2.022-3.235a.5.5 0 0 0 .013-.507z"/>
</svg></a>'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
